org: bjorgzen
app: aws-python-flask-dynamodb-api
service: aws-python-flask-dynamodb-api

frameworkVersion: "3"

provider:
    name: aws
    runtime: python3.8
    stage: dev
    iam:
        role:
            statements:
                - Effect: Allow
                  Action:
                      - dynamodb:Query
                      - dynamodb:Scan
                      - dynamodb:GetItem
                      - dynamodb:PutItem
                      - dynamodb:UpdateItem
                      - dynamodb:DeleteItem
                  Resource:
                      - Fn::GetAtt: [TodoTable, Arn]
    environment:
        TODO_TABLE: ${self:custom.tableName}

functions:
    app:
        handler: wsgi.handler
        events:
            - http: ANY /
            - http: "ANY /{proxy+}"

custom:
    tableName: "TODO_TABLE"
    wsgi:
        app: ./api/main.app
        packRequirements: false

plugins:
    - serverless-wsgi
    - serverless-python-requirements

resources:
    Resources:
        TodoTable:
            Type: AWS::DynamoDB::Table
            Properties:
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: S
                    - AttributeName: title
                      AttributeType: S
                    - AttributeName: description
                      AttributeType: S
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH
                ProvisionedThroughput:
                    ReadCapacityUnits: 1
                    WriteCapacityUnits: 1
                TableName: ${self:custom.tableName}
